modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="createcraft"
version="1.0.0"
displayName="CreateCraft"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="abnor, MCreator"

[[dependencies.createcraft]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




